package tfidf

import (
	"testing"
	"github.com/stretchr/testify/assert"
)

func TestStripSpacesLoop(t *testing.T) {
	testingDocument := `this

is  a
 	text

 	    shouldn't    be like    this`
	expectedDocument := "this is a text shouldn't be like this"

	actual := StripSpacesLoop(testingDocument)

	assert.Equal(t, expectedDocument, actual)
}

func TestStripSpacesRegex(t *testing.T) {
	testingDocument := `this

is  a
 	text

 	    shouldn't    be like    this`
	expectedDocument := "this is a text shouldn't be like this"

	actual := StripSpacesRegex(testingDocument)

	assert.Equal(t, expectedDocument, actual)
}

func BenchmarkStripSpacesLoop_Small_Text(b *testing.B) {
	testingDocument := "this  is  a     text shouldn't    be like    this"

	for i := 0; i < b.N; i++ {
		StripSpacesLoop(testingDocument)
	}
}

func BenchmarkStripSpacesRegex_Small_Text(b *testing.B) {
	testingDocument := "this  is  a     text shouldn't    be like    this"

	for i := 0; i < b.N; i++ {
		StripSpacesRegex(testingDocument)
	}
}

func BenchmarkStripSpacesLoop_Long_Text(b *testing.B) {
	testingDocument := `Early years (2000–2002)[edit]
In 2000, Iwata took a position at Nintendo as the head of its corporate planning division and took a seat on the board of directors.[5] Over the next two years, he sought to reduce the cost and length of game development while preserving quality.[24] During his first two years at Nintendo, the company saw profit increases of 20 and 41 percent, values which are at least partially attributable to his work.[16] When Yamauchi, the company's president since 1949, retired on May 24, 2002,[25][26] Iwata succeeded as Nintendo's fourth president with Yamauchi's blessing.[27] He was the first Nintendo president unrelated to the Yamauchi family through blood or marriage since its founding in 1889.[28] Yamauchi left the company in Iwata's hands with a final request: "that Nintendo give birth to wholly new ideas and create hardware which reflects that ideal. And make software that adheres to that same standard."[13] Iwata inherited a company that promoted individualism, with a policy established by Yamauchi to create new development positions as needed. However, this inhibited efficient collaboration between certain departments.[29]

At the time of Iwata's promotion, Nintendo, though still a profitable company, was not performing as well as other console makers. The recently released GameCube was performing poorly compared to competitors, with Sony's PlayStation 2 and Microsoft's Xbox outselling it.[2] His presidency also came at the onset of the popularization of online gaming, and Nintendo had yet to move into this facet of the market. He took a cautious approach to the issue, stating: "We're not negative toward the idea of going online. We're just practical."[30] He also fostered a relationship between Nintendo and Capcom that improved the GameCube's appeal.[13] During an interview in 2002, Iwata stated that he felt the gaming industry was becoming too exclusive, and he wanted to develop hardware and games that would appeal to all players rather than focusing on top of the line graphics.[30]

One of his first actions as president was to meet directly with the company's 40 department heads and 150 other employees. This contrasted starkly with Yamauchi's practice of rarely meeting with employees and generally having a single, annual speech. Shigeru Miyamoto described the previous business atmosphere as "stuffy" and stated Iwata "improved the ventilation."[31] Iwata was acutely aware that his position as president would not ensure compliance from his employees and sought to communicate with them on a personal level. If employees disagreed with his view, Iwata would suggest they follow their idea instead of his own, stating "creators only improve themselves by taking risks."[31] Alongside the increased level of interaction, Iwata also brought more data and science into the business aspect of the company. Whereas Yamauchi made decisions based on intuition and experience, Iwata brought forth hypotheses loaded with data to convey his position.[32] Iwata also promoted Miyamoto, Genyo Takeda, Yoshihiro Mori, and Shinji Hatano to representative directors on the company's board of directors, equaling his own position.[33][34]

Revitalization of the company (2003–09)[edit]
A blue variant of the original Nintendo DSThe Nintendo Wii and Wii Remote
Iwata directed Nintendo to produce the Nintendo DS (left) and Wii (right) units, which proved financially successful for the company.
Following up on his 2002 interview,[30] Iwata highlighted an urgency in the gaming market in his keynote speech at the 2003 Tokyo Game Show. During this speech, he reflected on the history of the industry and concluded with the declining interest in video games.[35] A slump in sales in the Japanese market had begun at the end of the 1990s and continued into the early 2000s. Competition between Nintendo and Sony resulted in increasingly hardware-heavy consoles; however, the Nintendo 64 proved to be too cumbersome for developers and software suffered severely.[36] After a year-long analysis conducted at Iwata's behest, Nintendo concluded that pushing hardware was not the most effective way to promote video games and decided to focus on software.[35] A major internal reorganization of Nintendo took place in 2004, with Iwata consolidating various departments established under Yamauchi. He sought to promote collaborative work throughout the company.[29] He later established a "User Expansion Project" in 2005 whereby employees normally not associated with game development would submit ideas for new games.[37]

In a March 2004 interview, Iwata stated: "Games have come to a dead end."[38] He stressed that developers wasted far too much time focusing on core gamers and would be unable to turn a profit if they did not tend to the average game player. Furthermore, he wished to prove that Nintendo, considered a "conservative" company at the time, would become a forefront innovator of entertainment.[38] Iwata articulated a "blue ocean" strategy to help Nintendo successfully compete against the other console manufactures. Instead of competing on technical specifications, Iwata drew on his previous experience as a game developer to produce novel and entertaining hardware and games.[1][7][9][13]

Nintendo DS[edit]
Iwata helped lead a revitalization of Nintendo's handheld business by transitioning the company from the Game Boy Advance to the Nintendo DS, which sported a unique form factor and inclusion of a touchscreen that allowed for novel games.[39] The idea for using two screens on a single device originated with Yamauchi before his retirement, while Miyamoto suggested the use of a touchscreen.[40] Miyamoto subsequently spearheaded development of the device and its prototypes.[41] The Nintendo DS proved to be a highly profitable system and went on to become the second-best selling video game console of all time with more than 154 million units, inclusive of subsequent iterations, sold by September 2014.[42][43] In June 2004, Iwata sought a conference with Dr. Ryuta Kawashima about a game that could appeal to non-gamers. This project would later become Brain Age: Train Your Brain in Minutes a Day!, released in May 2005.[7][44] Iwata personally oversaw development of the Brain Age series, even foregoing a public appearance on the day of the Nintendo DS's release in Japan on December 2.[44] Miyamoto supported Iwata's work with the series and sent one of his protégés, Kouichi Kawamoto, to help develop the game.[45] The Brain Age series is partially credited with launching the popularity of the Nintendo DS, and the series as a whole sold over 30 million copies by December 2008.[7][46]

Subsequent iterations of the Nintendo DS, the DS Lite and DSi, also saw positive sales.[47] The DS Lite improved upon the original DS, featuring brighter screens and a slimmer design in accordance with consumer demand.[48][49] Released in March 2006 in Japan and three months later worldwide,[48] the DS Lite ultimately sold nearly 94 million units.[42] Statistics showed that households often shared a single DS, and Iwata sought to expand this from one per household to one per person.[47] The console's third iteration, the DSi, embodies this idea with the "i" representing a single person.[50] Despite concerns that the video game market was already over saturated by the DS and DS Lite, Iwata was confident that the DSi would sell, especially in European markets.[51][52] The DSi built upon the success of the DS Lite by similarly meeting consumer demand.[50] In addition to being slimmed further, the DSi featured two cameras, SD card support, an audio reader, and the "Nintendo DSi Shop."[48] The relatively quick succession of the DS Lite and DSi broke the conventional pattern for release of game systems, each being released roughly 18 months apart instead of 5 years. Iwata saw the gradual price drop in the five-year cycle as a way of indirectly telling consumers to wait to purchase products and a punishment for those who bought it at launch. He sought to alleviate this issue with the quick releases.[50]

Wii[edit]
“	Video games are meant to be just one thing: fun. Fun for everyone.	”
— Satoru Iwata[53]
Discussions between Iwata, Miyamoto, and Takeda about a new home console began in the first half of 2003.[54] With encouragement from Yamauchi, Iwata pushed for development of a revolutionary product that would later become the Wii.[55] Iwata subsequently assigned Takeda to the project, "telling [Takeda] to go off the tech roadmap."[54] The overall premise was that "a Mom has to like it."[56] During the console's development process Iwata challenged engineers to make the Wii no thicker than three DVD cases stacked together, a feat they ultimately accomplished.[57] Takeda and his team focused on reducing power consumption while retaining or improving levels of performance shown with the GameCube.[58] Alongside the internal hardware designed by Nintendo's engineers, Iwata proposed that the console abandon use of a typical controller to make gaming more accessible to everyone.[55] Miyamoto took the lead on developing a new controller while Takeda's team provided the internal components. After six months and dozens of scrapped prototypes, Takeda procured a CMOS sensor that later became the core aspect of the remote. With the addition of accelerometers, they were able to effectively produce motion controls.[59]

Initially codenamed "Revolution" during a teaser at E3 2004, following Iwata's goal of creating a gaming revolution,[30][39] Iwata publicly revealed the Wii at E3 2005, holding it above his head to emphasize its small size and light weight design.[57] Reveal of the Wii's signature Wii Remote controller was withheld until the Tokyo Game Show in September 2005. During his speech at the conference, Iwata reiterated his stance on growing the gaming market but expanded upon it by emphasizing the need to make controls less complicated.[60] The controller's remote control design partially stemmed from Iwata's desire to have a device that was "immediately accessible" to all. He also insisted that the Wii Remote be referred to as simply a "remote" rather than a controller to emphasize its accessibility to anyone.[61]

The Wii ultimately popularized the use of motion control-based video games and proved highly successful for Nintendo, helping to nearly double the company's stock price.[39] Tapping into the market of casual players, the Wii marked "a breakthrough moment in the history of video games":[62] a new genre of gaming was established for the family market.[63] Iwata's former experience as a programmer, a rarity for technology CEOs, was said to help contribute towards his leadership of the company.[64][65] By the end of the 2009 fiscal year, Nintendo saw record net sales and profit of ¥1.8 trillion (US$18.7 billion) and ¥279 billion (US$2.8 billion), respectively.[66] Due to his success, Barron's included Iwata on their list of the 30 top CEOs worldwide from 2007 to 2009.[39][67]

Quality of life products[edit]
Starting with the introduction of the Wii in 2006, Iwata placed focus on development of products that improved quality of life.[68] The Wii Fit series, conceptualized by Miyamoto,[69] epitomized this movement.[68] At E3 2009, Iwata revealed development of an add-on product to the Wii: the Wii Vitality Sensor. The device measured autonomic nerve functions, namely pulse, and incorporate acquired data into relaxation products.[70][71] Iwata saw the device as a continuation of the "blue ocean" strategy previously articulated. He indicated that the market of motion controls was turning into a "red ocean," whereby too many companies would saturate the market and restrict profits. The Vitality Sensor was developed in hopes of providing a novel way to interact with video games and continue Nintendo's history of innovation.[72] However, testing of a prototype device yielded less than desirable results and Nintendo had postponed the release of the product indefinitely by 2013.[71]

In January 2014, Iwata unveiled a ten-year strategy for the company based on quality of life products.[68][73] The target was a new market outside video games.[74] Developed under partnerships with Dr. Yasuyoshi Watanabe and ResMed, the first device in this initiative was a fatigue and sleep deprivation sensor announced in October 2014. Unlike the Vitality Sensor, the sleep sensor was to be a stand-alone product that does not need to be worn.[75] Following Iwata's death in July 2015, analysts questioned whether Nintendo would continue the quality of life initiative. Despite a planned United States release in March 2016, some suggested the product had been temporarily shelved, while others believed the product had been indefinitely postponed like the Vitality Sensor before it.[68] The device was formally discontinued by February 2016; however, Tatsumi Kimishima stated that research into quality of life products would continue.[76]

Financial downturn (2010–14)[edit]
Nintendo net sales by fiscal year (2006–15)[nb 2]
Fiscal year				Sales (mil ¥)
2006[77]
  
508,827
2007[78]
  
966,534
2008[79]
  
1,672,423
2009[66]
  
1,838,622
2010[80]
  
1,182,177
2011[81]
  
1,014,345
2012[82]
  
647,652
2013[83]
  
635,422
2014[34]
  
571,726
2015[84]
  
549,780
Nintendo's annual net sales in millions of yen
Note: Green indicates an operating income while red indicates an operating loss.
Subsequent hardware units under Iwata's tenure, including the Nintendo 3DS and Wii U, were not as successful as the DS and Wii, and Nintendo's finances took a downward turn starting in 2010.[82][85] During the development phase of the 3DS, a handheld device featuring stereoscopic 3D without the need of accessories, Iwata stated that his background in technology helped keep Nintendo's engineers in line.[86] It was hoped that the successor to the Nintendo DS would reinvigorate the company after profits began declining.[87] However, weak sales upon the release of the Nintendo 3DS caused the company's stock to fall by 12 percent on July 29, 2011.[88] The console's poor sales prompted a price cut in August from its launch price of US$270 to US$170.[89] Sales of the 3DS continually fell below expectations.[90] Iwata later admitted in 2014 that he misread the market and did not appropriately account for changing lifestyles since the launch of the Wii.[91] He continually placed focus on family-oriented games despite declining popularity.[92]

The Wii U, released in November 2012,[93] was sold below its production cost as Nintendo hoped for stronger software sales to alleviate ongoing losses.[94] The addition of HD graphics, a feature not present in the original Wii, placed unexpected strain on development teams and led to software delays. Compounding the frustration of consumers was Iwata's disinterest in competitors such as Microsoft and Sony,[95][96] both of which experienced similar issues during the releases of the Xbox 360 and PlayStation 3 respectively. Paul Tassi of Forbes magazine claimed that Nintendo could have handled the change more efficiently by drawing lessons from Microsoft and Sony's transition to HD graphics.[97] The console ultimately failed to meet sales expectations and became the slowest-selling Nintendo platform, with 9.5 million units sold by June 2015. Miyamoto attributed the lackluster sales to public misunderstandings of the console's concept and functionality.[98] Iwata later admitted the console to be a failure as a successor to the Wii, with games being unable to showcase notable originality in the Wii U.[99] The back-to-back failures of the 3DS and Wii U prompted Mitsushige Akino of Ichiyoshi Asset Management Co. to suggest that Iwata should resign from his position.[92]

Nintendo's overall net sales declined from its peak of ¥1.8 trillion (US$18.7 billion) in 2009 to ¥549 billion (US$4.6 billion) in 2015. Net income losses were incurred in 2012 and 2014.[66][84] In 2010, Nintendo revealed that Iwata earned a modest salary of ¥68 million (US$770,000), which increased to ¥187 million (US$2.11 million) with performance based bonuses. In comparison, Miyamoto earned a salary of ¥100 million (US$1.13 million).[100] Iwata voluntarily halved his salary in 2011 and 2014 as apologies for the poor sales while other members of the Nintendo board of directors had pay cuts of 20–30 percent.[101][102] This also served to ensure the job security of Nintendo's employees, preventing workers from being laid off in order to improve short-term finances.[53][71] In 2012, the company experienced its first operating loss since entering the video game market more than 30 years earlier.[103] Losses continued for the next two years before the company finally returned to profitability at the end of the 2015 fiscal year.[84][85][104] The slight turnaround was largely attributed to blockbuster games such as Pokémon Omega Ruby and Alpha Sapphire and Super Smash Bros. for Nintendo 3DS and Wii U.[84][85]

In June 2013, Iwata took the additional role of Nintendo of America's CEO.[105][106] As one of his first changes as CEO, Iwata decided that they would not hold large press conferences at E3, and instead have several smaller events, each aimed at a certain demographic.[107] While traveling to Tokyo in late-2013, Iwata sketched an idea for a series of physical toys that could connect with Nintendo's games. This concept soon developed into the Amiibo line of figures which launched less than a year later. Amiibo proved to be a huge success, with more than 6 million figurine sold by the end of 2014, roughly a month after launch.[86] By March 2016, combined sales of figures and cards—a product released in 2015—exceeded 64 million units, proving financially beneficial across all Nintendo platforms.[108]

Mobile market (2015)[edit]
In early 2010, the success of Apple Inc.'s mobile App Store prompted concern among game developers that the medium was shifting to smart devices.[109] That July, Iwata acknowledged competition from Apple Inc. and considered them the "enemy of the future".[110] However, during an interview the following year Iwata appeared entirely against the idea of Nintendo moving into the mobile market, claiming the company would "cease to be Nintendo" if they did so.[111] He reasoned that mobile gaming would lack integrity over the quality of games in an effort to turn a profit. A slow shift in this view ensued over the following years as the mobile gaming market continued to grow.[112] In 2012 he acknowledged that mobile devices provided significant competition but remained confident in his company's abilities.[113] In a message to shareholders in March 2014 fiscal year, Iwata stated, "... I believe that the era has ended when people play all kinds of games only on dedicated gaming systems."[114] He cited the convenience of mobile devices for quick entertainment and expansive capabilities over a handheld console's dedicated software.[114] Criticism arose over his continued stubbornness in moving to the mobile market,[115] with analysts and investors continually requesting a change in outlook. Yoshihisa Toyosaki, president of Architect Grand Design Inc., claimed that "Nintendo is out of touch", referring to the company's history of ignoring outside input.[91] This ultimately negatively influenced Nintendo's finances and popularity to a degree.[116]

In March 2015, Iwata put part of Nintendo's focus on the growing mobile game market, creating a landmark partnership with mobile provider DeNA to publish titles, as traditional hardware console sales began to falter.[27][117] This came in stark contrast to the company's previous business model which put focus on console exclusive titles to prompt people to buy their platforms.[118] Iwata emphasized that although Nintendo IPs would be utilized in mobile games, the company would not compromise their integrity. He also stressed that the main goal would be to reach as many people as possible rather than which options would earn the most money, similar to the idea behind the Wii.[119] After the partnership with DeNA was established, Iwata reiterated his stance that the common free-to-play type mobile games, which he referred to as "free-to-start," threatened the future quality of games. Although he acknowledged the practice as a viable means of promoting titles in the short-term, he considered the model outdated and not a sound direction for core development.[112][120]

Public relations[edit]
refer to caption
Iwata was well known for incorporating his humor into his Nintendo Direct videos, such as during a pre-recorded video shown at E3 2012 when he stared at bananas in silence for several seconds before turning to the camera.[121]
See also: List of Iwata Asks interviews and List of Nintendo Direct presentations
During the earlier years of his presidency at Nintendo, Iwata would often forego media appearances, unless new hardware was being announced, in order to spend more time programming.[122] However, his attitude towards this changed, and he eventually became a prominent part of Nintendo's public relations. Iwata helped Nintendo to improve relations with its fans by regularly responding to them through social media,[65] and he shared insights on Nintendo's employees, games, and hardware through his interview series Iwata Asks.[64] Inspiration for this series, which began in September 2006, stemmed from Iwata's background as a game programmer and his curiosity of the mindset of other developers.[123][124] These interviews often showcased the friendly camaraderie between Iwata and other members of Nintendo as jokes and laughter were commonplace.[28] They also revealed a different side of the normally secretive Nintendo: openness to discuss some of the inner workings of the company.[125]

In 2011, Iwata helped to institute Nintendo Direct, a series of online press conferences open to all that revealed upcoming Nintendo games and products outside of typical industry channels.[65] These videos were often quirky and humorous, reflecting the personality of Iwata himself.[13] This stood completely against the generally serious tones displayed by Sony and Microsoft.[126] One such video displayed a mock battle between him and Nintendo of America President Reggie Fils-Aimé to showcase the inclusion of Mii characters, Nintendo digital avatars, in Super Smash Bros. for Nintendo 3DS and Wii U.[65][127] These frequently spurred the creation of Internet memes; such memes include the phrase "please understand" which was often used by Iwata for delays or other negative news, adding "[Iwata laughs]" to forum posts as a reference to his frequent laughter in segments of Iwata Asks, and images of Iwata staring silently at a bunch of bananas as part of a pre-recorded E3 2012 video to promote the Donkey Kong franchise.[7][121][128][129]

As a byproduct of his presence in Iwata Asks and Nintendo Direct, Iwata became the public face of Nintendo.[126] Iwata enjoyed conversing with reporters and would prepare stories in advance to entertain them. Even when time did not allow, he would mingle with interviewers and chat casually.[130]

Other projects[edit]
Iwata assisted in the founding of Creatures Inc., which was established in 1995 by Tsunekazu Ishihara.[131] In 1998, Iwata helped his colleague and personal friend Shigesato Itoi establish Hobonichi by working as the company's IT Manager. He acquired this position after being asked by Itoi one month prior to the June 6 launch date to arrange a website and the company's technical systems, to which Iwata complied. Iwata personally enjoyed the role and even still held the position in 2007, despite running Nintendo full-time by this point.[132] Soon after his promotion to president of Nintendo, Iwata assigned himself to a development team at HAL Laboratory working on Super Smash Bros. Melee, for the GameCube, to continue his programming passion.[9][133] Stemming from his work with the Brain Age series, Iwata assisted in producing educational titles such as Kanji Sonomama Rakubiki Jiten DS, English Training: Have Fun Improving Your Skills!, and Imasara Hito ni Kikenai Otona no Joushikiryoku Training DS.[134] He also worked on Animal Crossing, Mario, Metroid Prime, and the The Legend of Zelda series of games, among other titles.[16][135] He also had a cameo in WarioWare: Smooth Moves.[136] Iwata partook in the development of Pokémon GO, an augmented reality mobile game, starting in 2013. The game was publicly revealed two months after his death in September 2015.[137][138]

Illness and death[edit]
refer to caption
Fans left memorabilia and personalized artwork of various Nintendo video game series, including Mario, Kirby, and The Legend of Zelda, dedicated to Iwata at a memorial in the Nintendo World Store.
On June 5, 2014, Nintendo announced that Iwata would not be present at E3 2014 owing to medical-related reasons.[139] Iwata later issued a public message to shareholders on June 24 that he underwent surgery the previous week to remove a tumor in his bile duct that was discovered during a routine physical examination.[135][140] After roughly four months of recovery from a successful surgery, he returned to work in October. During this time he lost a notable amount of weight but stated to be feeling healthier as a result.[141] Iwata made his first public appearance on a Nintendo Direct announcement on November 5, but looked "gaunt and pale."[142] He appeared to take this in stride and updated his own Mii, avatars used in Nintendo hardware, in June 2015 to reflect his slimmer self.[143] On January 28, 2015, Iwata came down with a high fever and was suspected to have influenza; a meeting with shareholders was postponed accordingly.[144] At an unknown point after attending a different shareholder meeting on June 26, Iwata suddenly became ill again.[145] He later died due to complications with the tumor on July 11 at the age of 55. A formal announcement of his death was made by Nintendo the following day.[106]

Flags at Nintendo's headquarters were lowered to half-staff on July 13.[146] All of Nintendo's regional offices took a day of silence on July 13 across all of its social media accounts in remembrance of Iwata.[147] Members of the gaming industry and fans alike expressed their sadness on social media over Iwata's death and gratitude for his accomplishments.[146][148] Fans established memorials across the world, including at the Japanese Embassy in Moscow, Russia, and the Nintendo World Store in Manhattan, New York.[149][150] Shuhei Yoshida, president of SCE Worldwide Studios, stated: "I pray that Mr. Iwata, who contributed so much to the development of the gaming industry, rests in peace."[151] Composer and director Junichi Masuda, most known for his work with the Pokémon games, tweeted: "He was a man who understood Pokémon, and a great leader. When I visited the other day, he was well. I will pray for his soul from the bottom of my heart."[152] The Tokyo Institute of Technology issued a memorial statement on August 4, with Iwata's former classmates and professors contributing their memories.[10] At The Game Awards 2015, Reggie Fils-Aimé delivered a tribute to Iwata, describing Iwata as "fearless" and "unique, in the fullest meaning of the word."[153][154]

Several hours after the announcement of Iwata's death, a photograph of a rainbow over Nintendo's headquarters in Kyoto was posted to Twitter and widely shared; it was dubbed "the Rainbow Road to heaven," in reference to a stage in the Mario Kart series.[155][156] Funeral services for Iwata were held in Kyoto on July 16 and 17. Despite stormy weather produced by Typhoon Nangka, an estimated 4,100 people attended to pay their respects.[157][158][159] Following the wake, Iwata's remains were cremated.[160]

Following Iwata's death, general directors Shigeru Miyamoto and Genyo Takeda temporarily took over his former duties and managed the company together.[161] On September 14, Nintendo announced that Tatsumi Kimishima, head of its Human Resources Division and former CEO of Nintendo of America, would succeed Iwata as the fifth president of Nintendo`

	for i := 0; i < b.N; i++ {
		StripSpacesLoop(testingDocument)
	}
}

func BenchmarkStripSpacesRegex_Long_Text(b *testing.B) {
	testingDocument := `Early years (2000–2002)[edit]
In 2000, Iwata took a position at Nintendo as the head of its corporate planning division and took a seat on the board of directors.[5] Over the next two years, he sought to reduce the cost and length of game development while preserving quality.[24] During his first two years at Nintendo, the company saw profit increases of 20 and 41 percent, values which are at least partially attributable to his work.[16] When Yamauchi, the company's president since 1949, retired on May 24, 2002,[25][26] Iwata succeeded as Nintendo's fourth president with Yamauchi's blessing.[27] He was the first Nintendo president unrelated to the Yamauchi family through blood or marriage since its founding in 1889.[28] Yamauchi left the company in Iwata's hands with a final request: "that Nintendo give birth to wholly new ideas and create hardware which reflects that ideal. And make software that adheres to that same standard."[13] Iwata inherited a company that promoted individualism, with a policy established by Yamauchi to create new development positions as needed. However, this inhibited efficient collaboration between certain departments.[29]

At the time of Iwata's promotion, Nintendo, though still a profitable company, was not performing as well as other console makers. The recently released GameCube was performing poorly compared to competitors, with Sony's PlayStation 2 and Microsoft's Xbox outselling it.[2] His presidency also came at the onset of the popularization of online gaming, and Nintendo had yet to move into this facet of the market. He took a cautious approach to the issue, stating: "We're not negative toward the idea of going online. We're just practical."[30] He also fostered a relationship between Nintendo and Capcom that improved the GameCube's appeal.[13] During an interview in 2002, Iwata stated that he felt the gaming industry was becoming too exclusive, and he wanted to develop hardware and games that would appeal to all players rather than focusing on top of the line graphics.[30]

One of his first actions as president was to meet directly with the company's 40 department heads and 150 other employees. This contrasted starkly with Yamauchi's practice of rarely meeting with employees and generally having a single, annual speech. Shigeru Miyamoto described the previous business atmosphere as "stuffy" and stated Iwata "improved the ventilation."[31] Iwata was acutely aware that his position as president would not ensure compliance from his employees and sought to communicate with them on a personal level. If employees disagreed with his view, Iwata would suggest they follow their idea instead of his own, stating "creators only improve themselves by taking risks."[31] Alongside the increased level of interaction, Iwata also brought more data and science into the business aspect of the company. Whereas Yamauchi made decisions based on intuition and experience, Iwata brought forth hypotheses loaded with data to convey his position.[32] Iwata also promoted Miyamoto, Genyo Takeda, Yoshihiro Mori, and Shinji Hatano to representative directors on the company's board of directors, equaling his own position.[33][34]

Revitalization of the company (2003–09)[edit]
A blue variant of the original Nintendo DSThe Nintendo Wii and Wii Remote
Iwata directed Nintendo to produce the Nintendo DS (left) and Wii (right) units, which proved financially successful for the company.
Following up on his 2002 interview,[30] Iwata highlighted an urgency in the gaming market in his keynote speech at the 2003 Tokyo Game Show. During this speech, he reflected on the history of the industry and concluded with the declining interest in video games.[35] A slump in sales in the Japanese market had begun at the end of the 1990s and continued into the early 2000s. Competition between Nintendo and Sony resulted in increasingly hardware-heavy consoles; however, the Nintendo 64 proved to be too cumbersome for developers and software suffered severely.[36] After a year-long analysis conducted at Iwata's behest, Nintendo concluded that pushing hardware was not the most effective way to promote video games and decided to focus on software.[35] A major internal reorganization of Nintendo took place in 2004, with Iwata consolidating various departments established under Yamauchi. He sought to promote collaborative work throughout the company.[29] He later established a "User Expansion Project" in 2005 whereby employees normally not associated with game development would submit ideas for new games.[37]

In a March 2004 interview, Iwata stated: "Games have come to a dead end."[38] He stressed that developers wasted far too much time focusing on core gamers and would be unable to turn a profit if they did not tend to the average game player. Furthermore, he wished to prove that Nintendo, considered a "conservative" company at the time, would become a forefront innovator of entertainment.[38] Iwata articulated a "blue ocean" strategy to help Nintendo successfully compete against the other console manufactures. Instead of competing on technical specifications, Iwata drew on his previous experience as a game developer to produce novel and entertaining hardware and games.[1][7][9][13]

Nintendo DS[edit]
Iwata helped lead a revitalization of Nintendo's handheld business by transitioning the company from the Game Boy Advance to the Nintendo DS, which sported a unique form factor and inclusion of a touchscreen that allowed for novel games.[39] The idea for using two screens on a single device originated with Yamauchi before his retirement, while Miyamoto suggested the use of a touchscreen.[40] Miyamoto subsequently spearheaded development of the device and its prototypes.[41] The Nintendo DS proved to be a highly profitable system and went on to become the second-best selling video game console of all time with more than 154 million units, inclusive of subsequent iterations, sold by September 2014.[42][43] In June 2004, Iwata sought a conference with Dr. Ryuta Kawashima about a game that could appeal to non-gamers. This project would later become Brain Age: Train Your Brain in Minutes a Day!, released in May 2005.[7][44] Iwata personally oversaw development of the Brain Age series, even foregoing a public appearance on the day of the Nintendo DS's release in Japan on December 2.[44] Miyamoto supported Iwata's work with the series and sent one of his protégés, Kouichi Kawamoto, to help develop the game.[45] The Brain Age series is partially credited with launching the popularity of the Nintendo DS, and the series as a whole sold over 30 million copies by December 2008.[7][46]

Subsequent iterations of the Nintendo DS, the DS Lite and DSi, also saw positive sales.[47] The DS Lite improved upon the original DS, featuring brighter screens and a slimmer design in accordance with consumer demand.[48][49] Released in March 2006 in Japan and three months later worldwide,[48] the DS Lite ultimately sold nearly 94 million units.[42] Statistics showed that households often shared a single DS, and Iwata sought to expand this from one per household to one per person.[47] The console's third iteration, the DSi, embodies this idea with the "i" representing a single person.[50] Despite concerns that the video game market was already over saturated by the DS and DS Lite, Iwata was confident that the DSi would sell, especially in European markets.[51][52] The DSi built upon the success of the DS Lite by similarly meeting consumer demand.[50] In addition to being slimmed further, the DSi featured two cameras, SD card support, an audio reader, and the "Nintendo DSi Shop."[48] The relatively quick succession of the DS Lite and DSi broke the conventional pattern for release of game systems, each being released roughly 18 months apart instead of 5 years. Iwata saw the gradual price drop in the five-year cycle as a way of indirectly telling consumers to wait to purchase products and a punishment for those who bought it at launch. He sought to alleviate this issue with the quick releases.[50]

Wii[edit]
“	Video games are meant to be just one thing: fun. Fun for everyone.	”
— Satoru Iwata[53]
Discussions between Iwata, Miyamoto, and Takeda about a new home console began in the first half of 2003.[54] With encouragement from Yamauchi, Iwata pushed for development of a revolutionary product that would later become the Wii.[55] Iwata subsequently assigned Takeda to the project, "telling [Takeda] to go off the tech roadmap."[54] The overall premise was that "a Mom has to like it."[56] During the console's development process Iwata challenged engineers to make the Wii no thicker than three DVD cases stacked together, a feat they ultimately accomplished.[57] Takeda and his team focused on reducing power consumption while retaining or improving levels of performance shown with the GameCube.[58] Alongside the internal hardware designed by Nintendo's engineers, Iwata proposed that the console abandon use of a typical controller to make gaming more accessible to everyone.[55] Miyamoto took the lead on developing a new controller while Takeda's team provided the internal components. After six months and dozens of scrapped prototypes, Takeda procured a CMOS sensor that later became the core aspect of the remote. With the addition of accelerometers, they were able to effectively produce motion controls.[59]

Initially codenamed "Revolution" during a teaser at E3 2004, following Iwata's goal of creating a gaming revolution,[30][39] Iwata publicly revealed the Wii at E3 2005, holding it above his head to emphasize its small size and light weight design.[57] Reveal of the Wii's signature Wii Remote controller was withheld until the Tokyo Game Show in September 2005. During his speech at the conference, Iwata reiterated his stance on growing the gaming market but expanded upon it by emphasizing the need to make controls less complicated.[60] The controller's remote control design partially stemmed from Iwata's desire to have a device that was "immediately accessible" to all. He also insisted that the Wii Remote be referred to as simply a "remote" rather than a controller to emphasize its accessibility to anyone.[61]

The Wii ultimately popularized the use of motion control-based video games and proved highly successful for Nintendo, helping to nearly double the company's stock price.[39] Tapping into the market of casual players, the Wii marked "a breakthrough moment in the history of video games":[62] a new genre of gaming was established for the family market.[63] Iwata's former experience as a programmer, a rarity for technology CEOs, was said to help contribute towards his leadership of the company.[64][65] By the end of the 2009 fiscal year, Nintendo saw record net sales and profit of ¥1.8 trillion (US$18.7 billion) and ¥279 billion (US$2.8 billion), respectively.[66] Due to his success, Barron's included Iwata on their list of the 30 top CEOs worldwide from 2007 to 2009.[39][67]

Quality of life products[edit]
Starting with the introduction of the Wii in 2006, Iwata placed focus on development of products that improved quality of life.[68] The Wii Fit series, conceptualized by Miyamoto,[69] epitomized this movement.[68] At E3 2009, Iwata revealed development of an add-on product to the Wii: the Wii Vitality Sensor. The device measured autonomic nerve functions, namely pulse, and incorporate acquired data into relaxation products.[70][71] Iwata saw the device as a continuation of the "blue ocean" strategy previously articulated. He indicated that the market of motion controls was turning into a "red ocean," whereby too many companies would saturate the market and restrict profits. The Vitality Sensor was developed in hopes of providing a novel way to interact with video games and continue Nintendo's history of innovation.[72] However, testing of a prototype device yielded less than desirable results and Nintendo had postponed the release of the product indefinitely by 2013.[71]

In January 2014, Iwata unveiled a ten-year strategy for the company based on quality of life products.[68][73] The target was a new market outside video games.[74] Developed under partnerships with Dr. Yasuyoshi Watanabe and ResMed, the first device in this initiative was a fatigue and sleep deprivation sensor announced in October 2014. Unlike the Vitality Sensor, the sleep sensor was to be a stand-alone product that does not need to be worn.[75] Following Iwata's death in July 2015, analysts questioned whether Nintendo would continue the quality of life initiative. Despite a planned United States release in March 2016, some suggested the product had been temporarily shelved, while others believed the product had been indefinitely postponed like the Vitality Sensor before it.[68] The device was formally discontinued by February 2016; however, Tatsumi Kimishima stated that research into quality of life products would continue.[76]

Financial downturn (2010–14)[edit]
Nintendo net sales by fiscal year (2006–15)[nb 2]
Fiscal year				Sales (mil ¥)
2006[77]
  
508,827
2007[78]
  
966,534
2008[79]
  
1,672,423
2009[66]
  
1,838,622
2010[80]
  
1,182,177
2011[81]
  
1,014,345
2012[82]
  
647,652
2013[83]
  
635,422
2014[34]
  
571,726
2015[84]
  
549,780
Nintendo's annual net sales in millions of yen
Note: Green indicates an operating income while red indicates an operating loss.
Subsequent hardware units under Iwata's tenure, including the Nintendo 3DS and Wii U, were not as successful as the DS and Wii, and Nintendo's finances took a downward turn starting in 2010.[82][85] During the development phase of the 3DS, a handheld device featuring stereoscopic 3D without the need of accessories, Iwata stated that his background in technology helped keep Nintendo's engineers in line.[86] It was hoped that the successor to the Nintendo DS would reinvigorate the company after profits began declining.[87] However, weak sales upon the release of the Nintendo 3DS caused the company's stock to fall by 12 percent on July 29, 2011.[88] The console's poor sales prompted a price cut in August from its launch price of US$270 to US$170.[89] Sales of the 3DS continually fell below expectations.[90] Iwata later admitted in 2014 that he misread the market and did not appropriately account for changing lifestyles since the launch of the Wii.[91] He continually placed focus on family-oriented games despite declining popularity.[92]

The Wii U, released in November 2012,[93] was sold below its production cost as Nintendo hoped for stronger software sales to alleviate ongoing losses.[94] The addition of HD graphics, a feature not present in the original Wii, placed unexpected strain on development teams and led to software delays. Compounding the frustration of consumers was Iwata's disinterest in competitors such as Microsoft and Sony,[95][96] both of which experienced similar issues during the releases of the Xbox 360 and PlayStation 3 respectively. Paul Tassi of Forbes magazine claimed that Nintendo could have handled the change more efficiently by drawing lessons from Microsoft and Sony's transition to HD graphics.[97] The console ultimately failed to meet sales expectations and became the slowest-selling Nintendo platform, with 9.5 million units sold by June 2015. Miyamoto attributed the lackluster sales to public misunderstandings of the console's concept and functionality.[98] Iwata later admitted the console to be a failure as a successor to the Wii, with games being unable to showcase notable originality in the Wii U.[99] The back-to-back failures of the 3DS and Wii U prompted Mitsushige Akino of Ichiyoshi Asset Management Co. to suggest that Iwata should resign from his position.[92]

Nintendo's overall net sales declined from its peak of ¥1.8 trillion (US$18.7 billion) in 2009 to ¥549 billion (US$4.6 billion) in 2015. Net income losses were incurred in 2012 and 2014.[66][84] In 2010, Nintendo revealed that Iwata earned a modest salary of ¥68 million (US$770,000), which increased to ¥187 million (US$2.11 million) with performance based bonuses. In comparison, Miyamoto earned a salary of ¥100 million (US$1.13 million).[100] Iwata voluntarily halved his salary in 2011 and 2014 as apologies for the poor sales while other members of the Nintendo board of directors had pay cuts of 20–30 percent.[101][102] This also served to ensure the job security of Nintendo's employees, preventing workers from being laid off in order to improve short-term finances.[53][71] In 2012, the company experienced its first operating loss since entering the video game market more than 30 years earlier.[103] Losses continued for the next two years before the company finally returned to profitability at the end of the 2015 fiscal year.[84][85][104] The slight turnaround was largely attributed to blockbuster games such as Pokémon Omega Ruby and Alpha Sapphire and Super Smash Bros. for Nintendo 3DS and Wii U.[84][85]

In June 2013, Iwata took the additional role of Nintendo of America's CEO.[105][106] As one of his first changes as CEO, Iwata decided that they would not hold large press conferences at E3, and instead have several smaller events, each aimed at a certain demographic.[107] While traveling to Tokyo in late-2013, Iwata sketched an idea for a series of physical toys that could connect with Nintendo's games. This concept soon developed into the Amiibo line of figures which launched less than a year later. Amiibo proved to be a huge success, with more than 6 million figurine sold by the end of 2014, roughly a month after launch.[86] By March 2016, combined sales of figures and cards—a product released in 2015—exceeded 64 million units, proving financially beneficial across all Nintendo platforms.[108]

Mobile market (2015)[edit]
In early 2010, the success of Apple Inc.'s mobile App Store prompted concern among game developers that the medium was shifting to smart devices.[109] That July, Iwata acknowledged competition from Apple Inc. and considered them the "enemy of the future".[110] However, during an interview the following year Iwata appeared entirely against the idea of Nintendo moving into the mobile market, claiming the company would "cease to be Nintendo" if they did so.[111] He reasoned that mobile gaming would lack integrity over the quality of games in an effort to turn a profit. A slow shift in this view ensued over the following years as the mobile gaming market continued to grow.[112] In 2012 he acknowledged that mobile devices provided significant competition but remained confident in his company's abilities.[113] In a message to shareholders in March 2014 fiscal year, Iwata stated, "... I believe that the era has ended when people play all kinds of games only on dedicated gaming systems."[114] He cited the convenience of mobile devices for quick entertainment and expansive capabilities over a handheld console's dedicated software.[114] Criticism arose over his continued stubbornness in moving to the mobile market,[115] with analysts and investors continually requesting a change in outlook. Yoshihisa Toyosaki, president of Architect Grand Design Inc., claimed that "Nintendo is out of touch", referring to the company's history of ignoring outside input.[91] This ultimately negatively influenced Nintendo's finances and popularity to a degree.[116]

In March 2015, Iwata put part of Nintendo's focus on the growing mobile game market, creating a landmark partnership with mobile provider DeNA to publish titles, as traditional hardware console sales began to falter.[27][117] This came in stark contrast to the company's previous business model which put focus on console exclusive titles to prompt people to buy their platforms.[118] Iwata emphasized that although Nintendo IPs would be utilized in mobile games, the company would not compromise their integrity. He also stressed that the main goal would be to reach as many people as possible rather than which options would earn the most money, similar to the idea behind the Wii.[119] After the partnership with DeNA was established, Iwata reiterated his stance that the common free-to-play type mobile games, which he referred to as "free-to-start," threatened the future quality of games. Although he acknowledged the practice as a viable means of promoting titles in the short-term, he considered the model outdated and not a sound direction for core development.[112][120]

Public relations[edit]
refer to caption
Iwata was well known for incorporating his humor into his Nintendo Direct videos, such as during a pre-recorded video shown at E3 2012 when he stared at bananas in silence for several seconds before turning to the camera.[121]
See also: List of Iwata Asks interviews and List of Nintendo Direct presentations
During the earlier years of his presidency at Nintendo, Iwata would often forego media appearances, unless new hardware was being announced, in order to spend more time programming.[122] However, his attitude towards this changed, and he eventually became a prominent part of Nintendo's public relations. Iwata helped Nintendo to improve relations with its fans by regularly responding to them through social media,[65] and he shared insights on Nintendo's employees, games, and hardware through his interview series Iwata Asks.[64] Inspiration for this series, which began in September 2006, stemmed from Iwata's background as a game programmer and his curiosity of the mindset of other developers.[123][124] These interviews often showcased the friendly camaraderie between Iwata and other members of Nintendo as jokes and laughter were commonplace.[28] They also revealed a different side of the normally secretive Nintendo: openness to discuss some of the inner workings of the company.[125]

In 2011, Iwata helped to institute Nintendo Direct, a series of online press conferences open to all that revealed upcoming Nintendo games and products outside of typical industry channels.[65] These videos were often quirky and humorous, reflecting the personality of Iwata himself.[13] This stood completely against the generally serious tones displayed by Sony and Microsoft.[126] One such video displayed a mock battle between him and Nintendo of America President Reggie Fils-Aimé to showcase the inclusion of Mii characters, Nintendo digital avatars, in Super Smash Bros. for Nintendo 3DS and Wii U.[65][127] These frequently spurred the creation of Internet memes; such memes include the phrase "please understand" which was often used by Iwata for delays or other negative news, adding "[Iwata laughs]" to forum posts as a reference to his frequent laughter in segments of Iwata Asks, and images of Iwata staring silently at a bunch of bananas as part of a pre-recorded E3 2012 video to promote the Donkey Kong franchise.[7][121][128][129]

As a byproduct of his presence in Iwata Asks and Nintendo Direct, Iwata became the public face of Nintendo.[126] Iwata enjoyed conversing with reporters and would prepare stories in advance to entertain them. Even when time did not allow, he would mingle with interviewers and chat casually.[130]

Other projects[edit]
Iwata assisted in the founding of Creatures Inc., which was established in 1995 by Tsunekazu Ishihara.[131] In 1998, Iwata helped his colleague and personal friend Shigesato Itoi establish Hobonichi by working as the company's IT Manager. He acquired this position after being asked by Itoi one month prior to the June 6 launch date to arrange a website and the company's technical systems, to which Iwata complied. Iwata personally enjoyed the role and even still held the position in 2007, despite running Nintendo full-time by this point.[132] Soon after his promotion to president of Nintendo, Iwata assigned himself to a development team at HAL Laboratory working on Super Smash Bros. Melee, for the GameCube, to continue his programming passion.[9][133] Stemming from his work with the Brain Age series, Iwata assisted in producing educational titles such as Kanji Sonomama Rakubiki Jiten DS, English Training: Have Fun Improving Your Skills!, and Imasara Hito ni Kikenai Otona no Joushikiryoku Training DS.[134] He also worked on Animal Crossing, Mario, Metroid Prime, and the The Legend of Zelda series of games, among other titles.[16][135] He also had a cameo in WarioWare: Smooth Moves.[136] Iwata partook in the development of Pokémon GO, an augmented reality mobile game, starting in 2013. The game was publicly revealed two months after his death in September 2015.[137][138]

Illness and death[edit]
refer to caption
Fans left memorabilia and personalized artwork of various Nintendo video game series, including Mario, Kirby, and The Legend of Zelda, dedicated to Iwata at a memorial in the Nintendo World Store.
On June 5, 2014, Nintendo announced that Iwata would not be present at E3 2014 owing to medical-related reasons.[139] Iwata later issued a public message to shareholders on June 24 that he underwent surgery the previous week to remove a tumor in his bile duct that was discovered during a routine physical examination.[135][140] After roughly four months of recovery from a successful surgery, he returned to work in October. During this time he lost a notable amount of weight but stated to be feeling healthier as a result.[141] Iwata made his first public appearance on a Nintendo Direct announcement on November 5, but looked "gaunt and pale."[142] He appeared to take this in stride and updated his own Mii, avatars used in Nintendo hardware, in June 2015 to reflect his slimmer self.[143] On January 28, 2015, Iwata came down with a high fever and was suspected to have influenza; a meeting with shareholders was postponed accordingly.[144] At an unknown point after attending a different shareholder meeting on June 26, Iwata suddenly became ill again.[145] He later died due to complications with the tumor on July 11 at the age of 55. A formal announcement of his death was made by Nintendo the following day.[106]

Flags at Nintendo's headquarters were lowered to half-staff on July 13.[146] All of Nintendo's regional offices took a day of silence on July 13 across all of its social media accounts in remembrance of Iwata.[147] Members of the gaming industry and fans alike expressed their sadness on social media over Iwata's death and gratitude for his accomplishments.[146][148] Fans established memorials across the world, including at the Japanese Embassy in Moscow, Russia, and the Nintendo World Store in Manhattan, New York.[149][150] Shuhei Yoshida, president of SCE Worldwide Studios, stated: "I pray that Mr. Iwata, who contributed so much to the development of the gaming industry, rests in peace."[151] Composer and director Junichi Masuda, most known for his work with the Pokémon games, tweeted: "He was a man who understood Pokémon, and a great leader. When I visited the other day, he was well. I will pray for his soul from the bottom of my heart."[152] The Tokyo Institute of Technology issued a memorial statement on August 4, with Iwata's former classmates and professors contributing their memories.[10] At The Game Awards 2015, Reggie Fils-Aimé delivered a tribute to Iwata, describing Iwata as "fearless" and "unique, in the fullest meaning of the word."[153][154]

Several hours after the announcement of Iwata's death, a photograph of a rainbow over Nintendo's headquarters in Kyoto was posted to Twitter and widely shared; it was dubbed "the Rainbow Road to heaven," in reference to a stage in the Mario Kart series.[155][156] Funeral services for Iwata were held in Kyoto on July 16 and 17. Despite stormy weather produced by Typhoon Nangka, an estimated 4,100 people attended to pay their respects.[157][158][159] Following the wake, Iwata's remains were cremated.[160]

Following Iwata's death, general directors Shigeru Miyamoto and Genyo Takeda temporarily took over his former duties and managed the company together.[161] On September 14, Nintendo announced that Tatsumi Kimishima, head of its Human Resources Division and former CEO of Nintendo of America, would succeed Iwata as the fifth president of Nintendo`

	for i := 0; i < b.N; i++ {
		StripSpacesRegex(testingDocument)
	}
}
